global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:3025'
  smtp_require_tls: false
  smtp_from: 'amtest@localhost.localdomain'
  smtp_auth_username: 'user'
  smtp_auth_password: 'pass'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30s
  receiver: 'default-receiver'
receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'default-receiver@example.net'
